# Copyright Stefano Sinigardi

#.rst:
# FindSitaraSDK
# --------
#
# Result Variables
# ^^^^^^^^^^^^^^^^
#
# This module will set the following variables in your project:
#
#  ``SitaraSDK_FOUND``
#    True if SitaraSDK is found on the local system
#
#  ``SitaraSDK_INCLUDE_DIRS``
#    Location of SitaraSDK header files.
#
#  ``SitaraSDK_LIBRARY_DIRS``
#    Location of SitaraSDK library files.
#
#  ``SitaraSDK_LIBRARIES``
#    The SitaraSDK libraries
#

if(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
  set(SITARASDK_TI_BASE_FOLDER          "C:/ti")
  set(SITARASDK_RTOS_BASE_FOLDER        "${SITARASDK_TI_BASE_FOLDER}/tirtos_sitara_2_00_01_23" CACHE INTERNAL "")
  set(SITARASDK_COMPILER_BASE_FOLDER    "${SITARASDK_TI_BASE_FOLDER}/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS" CACHE INTERNAL "")
  set(SITARASDK_XDC_BASE_FOLDER         "${SITARASDK_TI_BASE_FOLDER}/xdctools_3_30_01_25_core/packages" CACHE INTERNAL "")
  set(SITARASDK_BIOS_BASE_FOLDER        "${SITARASDK_RTOS_BASE_FOLDER}/products/bios_6_40_01_15/packages" CACHE INTERNAL "")
  set(SITARASDK_NDK_BASE_FOLDER         "${SITARASDK_RTOS_BASE_FOLDER}/products/ndk_2_23_01_01/packages" CACHE INTERNAL "")
  set(SITARASDK_UIA_BASE_FOLDER         "${SITARASDK_RTOS_BASE_FOLDER}/products/uia_2_00_00_28/packages" CACHE INTERNAL "")
elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Darwin")
  set(SITARASDK_TI_BASE_FOLDER          "/Applications/ti")
  set(SITARASDK_COMPILER_BASE_FOLDER    "${SITARASDK_TI_BASE_FOLDER}/ti-cgt-arm_18.1.8.LTS" CACHE INTERNAL "")
  set(SITARASDK_XDC_BASE_FOLDER         "${SITARASDK_TI_BASE_FOLDER}/xdctools_3_61_02_27_core/packages" CACHE INTERNAL "")
  set(SITARASDK_BIOS_BASE_FOLDER        "${SITARASDK_TI_BASE_FOLDER}/bios_6_83_00_18/packages" CACHE INTERNAL "")
  set(SITARASDK_NDK_BASE_FOLDER         "${SITARASDK_TI_BASE_FOLDER}/ndk_2_25_01_11/packages" CACHE INTERNAL "")
else()
  set(SITARASDK_TI_BASE_FOLDER          "/opt/ti")
  set(SITARASDK_RTOS_BASE_FOLDER        "${SITARASDK_TI_BASE_FOLDER}/tirtos_sitara_2_00_01_23" CACHE INTERNAL "")
  set(SITARASDK_COMPILER_BASE_FOLDER    "${SITARASDK_TI_BASE_FOLDER}/ccs920/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS" CACHE INTERNAL "")
  set(SITARASDK_XDC_BASE_FOLDER         "${SITARASDK_TI_BASE_FOLDER}/xdctools_3_30_01_25_core/packages" CACHE INTERNAL "")
  set(SITARASDK_BIOS_BASE_FOLDER        "${SITARASDK_RTOS_BASE_FOLDER}/products/bios_6_40_01_15/packages" CACHE INTERNAL "")
  set(SITARASDK_NDK_BASE_FOLDER         "${SITARASDK_RTOS_BASE_FOLDER}/products/ndk_2_23_01_01/packages" CACHE INTERNAL "")
  set(SITARASDK_UIA_BASE_FOLDER         "${SITARASDK_RTOS_BASE_FOLDER}/products/uia_2_00_00_28/packages" CACHE INTERNAL "")
endif()

set(SITARASDK_LEGACY_COMPILER_BASE_FOLDER "${SITARASDK_TI_BASE_FOLDER}/ccsv6/tools/compiler/ti-cgt-arm_5.2.5" CACHE INTERNAL "")
set(SITARASDK_LEGACY_XDC_BASE_FOLDER      "${SITARASDK_TI_BASE_FOLDER}/xdctools_3_31_02_38_core/packages" CACHE INTERNAL "")
set(SITARASDK_LEGACY_BIOS_BASE_FOLDER     "${SITARASDK_TI_BASE_FOLDER}/bios_6_42_02_29/packages" CACHE INTERNAL "")
set(SITARASDK_LEGACY_NDK_BASE_FOLDER      "${SITARASDK_TI_BASE_FOLDER}/ndk_2_24_03_35/packages" CACHE INTERNAL "")

include(SelectLibraryConfigurations)
include(FindPackageHandleStandardArgs)

find_library(SITARASDK_LIBC NAMES libc c PATHS ${SITARASDK_COMPILER_BASE_FOLDER}/lib NO_DEFAULT_PATH)
get_filename_component(SITARASDK_LIBC_PATH ${SITARASDK_LIBC} DIRECTORY)

find_path(SITARASDK_COMPILER_INCLUDE_DIR stdarg.h             PATHS ${SITARASDK_COMPILER_BASE_FOLDER}/include NO_DEFAULT_PATH)
find_path(SITARASDK_XDC_INCLUDE_DIR      xdc/std.h            PATHS ${SITARASDK_XDC_BASE_FOLDER} NO_DEFAULT_PATH)
find_path(SITARASDK_NDK_INCLUDE_DIR      ti/ndk/inc/netmain.h PATHS ${SITARASDK_NDK_BASE_FOLDER} NO_DEFAULT_PATH)
find_path(SITARASDK_NDK_INT_INCLUDE_DIR  netmain.h            PATHS ${SITARASDK_NDK_BASE_FOLDER}/ti/ndk/inc NO_DEFAULT_PATH)
find_path(SITARASDK_SYSBIOS_INCLUDE_DIR  ti/sysbios/BIOS.h    PATHS ${SITARASDK_BIOS_BASE_FOLDER} NO_DEFAULT_PATH)

find_library(SITARASDK_LEGACY_LIBC NAMES libc c PATHS ${SITARASDK_LEGACY_COMPILER_BASE_FOLDER}/lib NO_DEFAULT_PATH)
get_filename_component(SITARASDK_LEGACY_LIBC_PATH ${SITARASDK_LEGACY_LIBC} DIRECTORY)

find_path(SITARASDK_LEGACY_COMPILER_INCLUDE_DIR stdarg.h             PATHS ${SITARASDK_LEGACY_COMPILER_BASE_FOLDER}/include NO_DEFAULT_PATH)
find_path(SITARASDK_LEGACY_XDC_INCLUDE_DIR      xdc/std.h            PATHS ${SITARASDK_LEGACY_XDC_BASE_FOLDER} NO_DEFAULT_PATH)
find_path(SITARASDK_LEGACY_NDK_INCLUDE_DIR      ti/ndk/inc/netmain.h PATHS ${SITARASDK_LEGACY_NDK_BASE_FOLDER} NO_DEFAULT_PATH)
find_path(SITARASDK_LEGACY_NDK_INT_INCLUDE_DIR  netmain.h            PATHS ${SITARASDK_LEGACY_NDK_BASE_FOLDER}/ti/ndk/inc NO_DEFAULT_PATH)
find_path(SITARASDK_LEGACY_SYSBIOS_INCLUDE_DIR  ti/sysbios/BIOS.h    PATHS ${SITARASDK_LEGACY_BIOS_BASE_FOLDER} NO_DEFAULT_PATH)

list(APPEND SitaraSDK_LEGACY_INCLUDE_DIRS "${SITARASDK_LEGACY_COMPILER_INCLUDE_DIR}")
list(APPEND SitaraSDK_LEGACY_INCLUDE_DIRS "${SITARASDK_LEGACY_XDC_INCLUDE_DIR}")
list(APPEND SitaraSDK_LEGACY_INCLUDE_DIRS "${SITARASDK_LEGACY_NDK_INCLUDE_DIR}")
list(APPEND SitaraSDK_LEGACY_INCLUDE_DIRS "${SITARASDK_LEGACY_NDK_INT_INCLUDE_DIR}")
list(APPEND SitaraSDK_LEGACY_INCLUDE_DIRS "${SITARASDK_LEGACY_SYSBIOS_INCLUDE_DIR}")

list(APPEND SitaraSDK_INCLUDE_DIRS "${SITARASDK_COMPILER_INCLUDE_DIR}")
list(APPEND SitaraSDK_INCLUDE_DIRS "${SITARASDK_XDC_INCLUDE_DIR}")
list(APPEND SitaraSDK_INCLUDE_DIRS "${SITARASDK_NDK_INCLUDE_DIR}")
list(APPEND SitaraSDK_INCLUDE_DIRS "${SITARASDK_NDK_INT_INCLUDE_DIR}")
list(APPEND SitaraSDK_INCLUDE_DIRS "${SITARASDK_SYSBIOS_INCLUDE_DIR}")
list(APPEND SitaraSDK_LIBARY_DIRS "${SITARASDK_LIBC_PATH}")
list(APPEND SitaraSDK_LIBRARIES "${SITARASDK_LIBC}")

find_package_handle_standard_args(SitaraSDK
      DEFAULT_MSG  SitaraSDK_LIBRARIES SitaraSDK_INCLUDE_DIRS SitaraSDK_LIBARY_DIRS
)
