BeforeAll {
    $moduleRoot = Split-Path -Parent $PSScriptRoot
    Import-Module (Join-Path $moduleRoot "CCM.psd1") -Force
}

Describe "Resolve-CcmEcsWebUiUrl" {

    Context "explicit override" {
        It "returns the caller-supplied URL verbatim, ignoring everything else" {
            $path = Join-Path $TestDrive "infra-override.json"
            @{ AlbDns = "alb.example.com"; ListenerProtocol = "HTTP" } |
                ConvertTo-Json | Set-Content -Path $path

            Resolve-CcmEcsWebUiUrl `
                -WebUiUrl "https://preview.example.com/_pr/42" `
                -InfrastructureConfigPath $path |
                Should -Be "https://preview.example.com/_pr/42"
        }

        It "wins even when no infrastructure config exists at all" {
            Resolve-CcmEcsWebUiUrl `
                -WebUiUrl "http://preview.example.com/_pr/7" `
                -InfrastructureConfigPath (Join-Path $TestDrive "does-not-exist.json") |
                Should -Be "http://preview.example.com/_pr/7"
        }
    }

    Context "resolution from infrastructure config" {
        It "falls back to AlbDns over http when no other host is configured" {
            $path = Join-Path $TestDrive "infra-alb.json"
            @{ AlbDns = "alb.example.com"; ListenerProtocol = "HTTP" } |
                ConvertTo-Json | Set-Content -Path $path

            Resolve-CcmEcsWebUiUrl -InfrastructureConfigPath $path |
                Should -Be "http://alb.example.com"
        }

        It "uses https when the listener protocol is HTTPS" {
            $path = Join-Path $TestDrive "infra-https.json"
            @{ AlbDns = "alb.example.com"; ListenerProtocol = "HTTPS" } |
                ConvertTo-Json | Set-Content -Path $path

            Resolve-CcmEcsWebUiUrl -InfrastructureConfigPath $path |
                Should -Be "https://alb.example.com"
        }

        It "prefers NlbDns over AlbDns" {
            $path = Join-Path $TestDrive "infra-nlb.json"
            @{ AlbDns = "alb.example.com"; NlbDns = "nlb.example.com"; ListenerProtocol = "HTTP" } |
                ConvertTo-Json | Set-Content -Path $path

            Resolve-CcmEcsWebUiUrl -InfrastructureConfigPath $path |
                Should -Be "http://nlb.example.com"
        }

        It "prefers the config's CustomDomainName over NlbDns and AlbDns" {
            $path = Join-Path $TestDrive "infra-custom.json"
            @{
                AlbDns           = "alb.example.com"
                NlbDns           = "nlb.example.com"
                CustomDomainName = "app.example.com"
                ListenerProtocol = "HTTPS"
            } | ConvertTo-Json | Set-Content -Path $path

            Resolve-CcmEcsWebUiUrl -InfrastructureConfigPath $path |
                Should -Be "https://app.example.com"
        }

        It "prefers an explicitly passed CustomDomainName over every config host" {
            $path = Join-Path $TestDrive "infra-precedence.json"
            @{
                AlbDns           = "alb.example.com"
                NlbDns           = "nlb.example.com"
                CustomDomainName = "config.example.com"
                ListenerProtocol = "HTTPS"
            } | ConvertTo-Json | Set-Content -Path $path

            Resolve-CcmEcsWebUiUrl `
                -InfrastructureConfigPath $path `
                -CustomDomainName "explicit.example.com" |
                Should -Be "https://explicit.example.com"
        }
    }

    Context "missing or unusable infrastructure config" {
        # This is the CI regression: deploy/ecs/infrastructure-config.json is
        # generated by setup-aws-infrastructure.ps1 and was gitignored, so the
        # build agent's fresh clone had no file and the deploy summary silently
        # printed no address at all.
        It "returns null when the config file does not exist and nothing else is known" {
            Resolve-CcmEcsWebUiUrl `
                -InfrastructureConfigPath (Join-Path $TestDrive "absent.json") |
                Should -BeNullOrEmpty
        }

        It "still resolves a URL from CustomDomainName when the config file is absent" {
            Resolve-CcmEcsWebUiUrl `
                -InfrastructureConfigPath (Join-Path $TestDrive "absent.json") `
                -CustomDomainName "app.example.com" |
                Should -Be "http://app.example.com"
        }

        It "returns null when the config exists but carries no host at all" {
            $path = Join-Path $TestDrive "infra-hostless.json"
            @{ ListenerProtocol = "HTTP"; TargetGroupArn = "arn:aws:elasticloadbalancing:::x" } |
                ConvertTo-Json | Set-Content -Path $path

            Resolve-CcmEcsWebUiUrl -InfrastructureConfigPath $path | Should -BeNullOrEmpty
        }

        It "returns null instead of throwing when the config file is malformed JSON" {
            $path = Join-Path $TestDrive "infra-broken.json"
            Set-Content -Path $path -Value "{ this is not json"

            Resolve-CcmEcsWebUiUrl -InfrastructureConfigPath $path | Should -BeNullOrEmpty
        }

        It "returns null when no arguments identify a host" {
            Resolve-CcmEcsWebUiUrl | Should -BeNullOrEmpty
        }
    }
}
