function Resolve-CcmEcsWebUiUrl {
    <#
    .SYNOPSIS
    Resolves the public web address of a deployed ECS service.

    .DESCRIPTION
    Applies the standard host precedence used by the deploy scripts and returns a full
    URL, or $null when no host can be determined.

    Precedence:
      1. -WebUiUrl            explicit override, returned verbatim (preview deploys pass
                              the full PR URL including its /_pr/<id> path prefix)
      2. -CustomDomainName    caller/ecs-config.json value
      3. config CustomDomainName
      4. config NlbDns
      5. config AlbDns

    The scheme is https when the infrastructure config reports ListenerProtocol HTTPS,
    otherwise http.

    A missing or malformed infrastructure config is not an error: the function degrades
    to whatever the caller supplied and returns $null if that leaves no host. Callers
    should treat $null as "address unknown" and say so, rather than printing nothing --
    deploy/ecs/infrastructure-config.json is generated by setup-aws-infrastructure.ps1
    and is absent whenever it has not been committed to the repository.

    .PARAMETER WebUiUrl
    Explicit URL that overrides all other resolution.

    .PARAMETER InfrastructureConfigPath
    Path to deploy/ecs/infrastructure-config.json. May be absent or unreadable.

    .PARAMETER CustomDomainName
    Custom domain that outranks every host recorded in the infrastructure config.

    .EXAMPLE
    Resolve-CcmEcsWebUiUrl -InfrastructureConfigPath ./deploy/ecs/infrastructure-config.json
    http://my-app-alb-1234567890.eu-central-1.elb.amazonaws.com
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [string]$WebUiUrl,

        [string]$InfrastructureConfigPath,

        [string]$CustomDomainName
    )

    if (-not [string]::IsNullOrWhiteSpace($WebUiUrl)) {
        return $WebUiUrl.Trim()
    }

    $infra = $null
    if (-not [string]::IsNullOrWhiteSpace($InfrastructureConfigPath) -and (Test-Path $InfrastructureConfigPath)) {
        try {
            $raw = Get-Content $InfrastructureConfigPath -Raw -ErrorAction Stop
            if (-not [string]::IsNullOrWhiteSpace($raw)) {
                $infra = $raw | ConvertFrom-Json -ErrorAction Stop
            }
        }
        catch {
            Write-Verbose "Ignoring unreadable infrastructure config '$InfrastructureConfigPath': $($_.Exception.Message)"
            $infra = $null
        }
    }

    $displayHost = @(
        $CustomDomainName
        $infra.CustomDomainName
        $infra.NlbDns
        $infra.AlbDns
    ) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -First 1

    if ([string]::IsNullOrWhiteSpace($displayHost)) {
        return $null
    }

    $protocol = if ($infra.ListenerProtocol -eq "HTTPS") { "https" } else { "http" }

    return "${protocol}://$($displayHost.Trim())"
}
